apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: playwright
          image: localhost/playwright-ui-api-framework:latest
          imagePullPolicy: IfNotPresent
          command: ["npm", "test"]
          envFrom:
            - configMapRef:
                name: playwright-config