name: Playwright Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Playwright image
        run: docker build -t playwright-ui-api-framework:latest .

      - name: Run Playwright tests
        run: docker run --rm \
          -e UI_BASE_URL=https://eventhub.rahulshettyacademy.com \
          -e API_BASE_URL=https://api.eventhub.rahulshettyacademy.com/api/ \
          playwright-ui-api-framework:latest